package nl.tudelft.atlarge.writer.install;

import nl.tudelft.atlarge.writer.packages.ProductPackage;
import nl.tudelft.atlarge.writer.script.ShellScriptBuilder;

/**
 * Created by Chris Lemaire on 29-8-2017.
 */
public class ArchivedProductInstallScriptWriter {

    private ProductArchive productArchive;

    private ShellScriptBuilder builder;

    private String product;

    public ArchivedProductInstallScriptWriter(ShellScriptBuilder builder, String product) {
        this.productArchive = new ProductArchive(product);
        this.builder = builder;
        this.product = product;
    }

    public void write(String version) {
        if (!productArchive.hasVersion(version)) {
            System.err.println("Unable to write downloader for version `" + version + "`.");
            System.err.println("This version does not exist.");
        }

        builder.appendLine("# START OF ARCHIVE DOWNLOADING SCRIPT #")
                .appendLine("# Generated by " + getClass().getName() + ".")
                .appendLine("# Intended product + version: " + product + "-" + version)
                .appendLine("cd " + builder.getCurrentRemoteSystem().frameworks())

                .appendLine("mkdir -p ./" + product + "/" + version)
                .appendLine("cd ./" + product + "/" + version)

                .appendLine("if [ -z \"$(ls -A ./)\" ]; then");

        ProductPackage.TAR_GZ.downloadAndUnpack(builder, productArchive.getLink(version))
        
                .appendLine("else")                

                .appendLineWithOutput("echo Product already installed: " + product + " v" + version)
                .appendLine("fi")
                .appendLine("# END OF ARCHIVE DOWNLOADING SCRIPT #\n\n");
    }

}
