package nl.tudelft.atlarge.gdeploy.install;

import nl.tudelft.atlarge.gdeploy.core.script.PythonScriptBuilder;

/**
 * Created by Chris Lemaire on 5-9-2017.
 */
public abstract class InstallScriptWriter {

    protected PythonScriptBuilder builder;

    protected String product;

    protected InstallScriptWriter(PythonScriptBuilder builder, String product) {
        this.builder = builder;
        this.product = product;
    }

    protected PythonScriptBuilder writeInitializer(String version) {
        builder.appendLine("# Generated by " + getClass().getName() + ".")
                .appendLine("# Intended product + version: " + product + "-" + version)
                .appendLine("cd " + builder.getCurrentRemoteSystem().frameworks())

                .appendLine("mkdir -p ./" + product + "/" + version)
                .appendLine("cd ./" + product + "/" + version);

        return builder;
    }

    public abstract PythonScriptBuilder write(String version);

}
